export default {
  'solar:text-bold': async () => (await import('~icons/solar/text-bold')).default,
  'fluent:shapes-24-regular': async () => (await import('~icons/fluent/shapes-24-regular')).default,
  'mage:image-fill': async () => (await import('~icons/mage/image-fill')).default,
  'mdi:plus': async () => (await import('~icons/mdi/plus')).default,
  'tabler:error-404': async () => (await import('~icons/tabler/error-404')).default,
  'weui:arrow-filled': async () => (await import('~icons/weui/arrow-filled')).default,
  'weui:arrow-outlined': async () => (await import('~icons/weui/arrow-outlined')).default,
  'uil:line-alt': async () => (await import('~icons/uil/line-alt')).default,
  'majesticons:table': async () => (await import('~icons/majesticons/table')).default,
  'ajesticons:table': async () => (await import('~icons/ajesticons/table')).default,
  'teenyicons:donut-chart-solid': async () => (await import('~icons/teenyicons/donut-chart-solid')).default,
  'mynaui:heading-one': async () => (await import('~icons/mynaui/heading-one')).default,
  'mynaui:heading-two': async () => (await import('~icons/mynaui/heading-two')).default,
  'mynaui:heading-three': async () => (await import('~icons/mynaui/heading-three')).default,
  'mynaui:heading-four': async () => (await import('~icons/mynaui/heading-four')).default,
  'mynaui:heading-five': async () => (await import('~icons/mynaui/heading-five')).default,
  'solar:widget-2-bold': async () => (await import('~icons/solar/widget-2-bold')).default,
  'solar:palette-bold': async () => (await import('~icons/solar/palette-bold')).default,
  'solar:bolt-bold': async () => (await import('~icons/solar/bolt-bold')).default,
  'solar:download-bold': async () => (await import('~icons/solar/download-bold')).default,
  'solar:add-circle-bold': async () => (await import('~icons/solar/add-circle-bold')).default,
  'solar:eye-bold': async () => (await import('~icons/solar/eye-bold')).default,
  'solar:arrow-right-bold': async () => (await import('~icons/solar/arrow-right-bold')).default,
};
